name: "sports"
version: "1.0.0"
config-version: 2

# Need to switch this to "{{ env_var('DBT_PROFILE') }}" soon!
profile: "sports"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  enable_nba_contracts: false
  dbt_osmosis_default_path: "{model}.yml"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  sports:
    +persist_docs:
      relation: true
      columns: true

    +materialized: view
    +static_analysis: strict

    staging:
      nba:
        kaggle:
          +schema: kaggle
          +materialized: table

        elo:
          +schema: elo
          +materialized: table

        betting:
          +schema: betting
          +materialized: table

        contracts:
          +schema: contracts
          +materialized: table
          +enabled: "{{ var('enable_nba_contracts', false) }}"

        custom:
          +schema: custom
          +materialized: table

    sports:
      nba:
        kaggle:
          +schema: kaggle

        elo:
          +schema: elo

        betting:
          +schema: betting

        contracts:
          +schema: contracts
          +enabled: "{{ var('enable_nba_contracts', false) }}"

        custom:
          +schema: custom