sports:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: belayground-467323
      dataset: nba_staging
      threads: 4
      timeout_seconds: 300
      location: us-south1
    prod:
      type: bigquery
      method: oauth
      project: belayground-467323
      dataset: nba
      threads: 4
      timeout_seconds: 300
      location: us-south1
