sports:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: belayground-467323
      dataset: nba_staging
      threads: 4
      timeout_seconds: 300
      location: us-south1
    prod:
      type: bigquery
      method: service-account
      project: belayground-467323
      dataset: dbt
      threads: 4
      timeout_seconds: 300
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: us-south1
