{{ config(materialized='table') }}

select
    safe_cast(`firstName` as string) as first_name,
    safe_cast(`lastName` as string) as last_name,
    safe_cast(`personId` as int64) as person_id,
    safe_cast(`gameId` as int64) as game_id,
    safe_cast(`gameDateTimeEst` as timestamp) as game_date_time_est,
    safe_cast(`playerteamCity` as string) as player_team_city,
    safe_cast(`playerteamName` as string) as player_team_name,
    safe_cast(`opponentteamCity` as string) as opponent_team_city,
    safe_cast(`opponentteamName` as string) as opponent_team_name,
    safe_cast(`gameType` as string) as game_type,
    safe_cast(`gameLabel` as string) as game_label,
    safe_cast(`seriesGameNumber` as string) as series_game_number,
    safe_cast(`gameSubLabel` as string) as game_sub_label,
    safe_cast(`win` as int64) as win,
    safe_cast(`home` as int64) as home,
    safe_cast(`numMinutes` as float64) as num_minutes,
    safe_cast(`points` as int64) as points,
    safe_cast(`assists` as int64) as assists,
    safe_cast(`blocks` as int64) as blocks,
    safe_cast(`steals` as int64) as steals,
    safe_cast(`fieldGoalsAttempted` as int64) as field_goals_attempted,
    safe_cast(`fieldGoalsMade` as int64) as field_goals_made,
    safe_cast(`fieldGoalsPercentage` as float64) as field_goals_percentage,
    safe_cast(`threePointersAttempted` as int64) as three_pointers_attempted,
    safe_cast(`threePointersMade` as int64) as three_pointers_made,
    safe_cast(`threePointersPercentage` as float64) as three_pointers_percentage,
    safe_cast(`freeThrowsAttempted` as int64) as free_throws_attempted,
    safe_cast(`freeThrowsMade` as int64) as free_throws_made,
    safe_cast(`freeThrowsPercentage` as float64) as free_throws_percentage,
    safe_cast(`reboundsDefensive` as int64) as rebounds_defensive,
    safe_cast(`reboundsOffensive` as int64) as rebounds_offensive,
    safe_cast(`reboundsTotal` as int64) as rebounds_total,
    safe_cast(`foulsPersonal` as int64) as fouls_personal,
    safe_cast(`turnovers` as int64) as turnovers,
    safe_cast(`plusMinusPoints` as int64) as plus_minus_points,
    safe_cast(`playerteamId` as int64) as player_team_id,
    safe_cast(`opponentteamId` as int64) as opponent_team_id,
    safe_cast(`comment` as string) as comment,
    safe_cast(`startingPosition` as string) as starting_position,
    safe_cast(`gameDate` as date) as game_date

from {{ source('nba_raw', 'player_statistics') }}
