{{
    config(
        materialized='view'
    )
}}

select
    first_name,
    last_name,
    person_id,
    game_id,
    game_date_time_est as game_datetime_est,
    regexp_replace(
        lower(concat(extract(year from date(game_date_time_est)), game_label)), r'[^a-z0-9]', ''
    ) as series_id,
    game_type,
    case
        when game_label is null then null
        else replace(game_label, '- ', '')
    end as game_label,
    cast(case
        when series_game_number like "%1%" then "1"
        else series_game_number end as float64
    ) as series_game_number,
    game_sub_label,
    win,
    home,
    player_team_id,
    player_team_city,
    player_team_name,
    opponent_team_id,
    opponent_team_city,
    opponent_team_name,
    comment,
    starting_position,
    num_minutes,
    points,
    assists,
    rebounds_total,
    rebounds_offensive,
    rebounds_defensive,
    field_goals_made,
    field_goals_attempted,
    field_goals_percentage,
    three_pointers_made,
    three_pointers_attempted,
    three_pointers_percentage,
    free_throws_made,
    free_throws_attempted,
    free_throws_percentage,
    steals,
    blocks,
    blocks_against,
    turnovers,
    fouls_personal,
    fouls_against,
    plus_minus_points,
    double_double,
    triple_double,
    estimated_offensive_rating,
    offensive_rating,
    sp_work_offensive_rating,
    estimated_defensive_rating,
    defensive_rating,
    sp_work_defensive_rating,
    estimated_net_rating,
    net_rating,
    sp_work_net_rating,
    assist_percentage,
    assist_to_turnover_ratio,
    assist_ratio,
    offensive_rebound_percentage,
    defensive_rebound_percentage,
    rebound_percentage,
    team_turnover_percentage,
    estimated_turnover_percentage,
    effective_field_goal_percentage,
    true_shooting_percentage,
    usage_percentage,
    estimated_usage_percentage,
    estimated_pace,
    pace,
    pace_per_40,
    sp_work_pace,
    player_impact_estimate,
    possessions,
    points_off_turnovers,
    points_second_chance,
    points_fast_break,
    points_in_paint,
    opponent_points_off_turnovers,
    opponent_points_second_chance,
    opponent_points_fast_break,
    opponent_points_in_paint,
    percent_field_goal_attempts_2_point,
    percent_field_goal_attempts_3_point,
    percent_points_2_point,
    percent_points_2_point_mid_range,
    percent_points_3_point,
    percent_points_fast_break,
    percent_points_free_throw,
    percent_points_off_turnovers,
    percent_points_in_paint,
    percent_assisted_2_point_made,
    percent_unassisted_2_point_made,
    percent_assisted_3_point_made,
    percent_unassisted_3_point_made,
    percent_assisted_field_goals_made,
    percent_unassisted_field_goals_made,
    percent_team_field_goals_made,
    percent_team_field_goals_attempted,
    percent_team_three_pointers_made,
    percent_team_three_pointers_attempted,
    percent_team_free_throws_made,
    percent_team_free_throws_attempted,
    percent_team_offensive_rebounds

from {{ ref('stg_nba_kaggle_player_statistics_extended') }}
