{{
    config(
        materialized='view',
        schema='nba'
    )
}}

select
    `clock`,
    `actionType` as action_type,
    `description`,
    `playerFullName` as player_full_name,
    `teamTricode` as team_tricode,
    `gameId` as game_id,
    `gameDateTimeEst` as game_datetime_est,
    `periodType` as period_type,
    `period` as period,
    `shortFormattedClock` as short_formatted_clock,
    `timeActual` as time_actual,
    `actionNumber` as action_number,
    `orderNumber` as order_number,
    `actionId` as action_id,
    `teamId` as team_id,
    `side` as side,
    `location` as location,
    `playerteamCity` as player_team_city,
    `playerteamName` as player_team_name,
    `opponentteamCity` as opponent_team_city,
    `opponentteamName` as opponent_team_name,
    `scoreHome` as score_home,
    `scoreAway` as score_away,
    `possession` as possession,
    `isTargetScoreLastPeriod`,
    `subType` as sub_type,
    `descriptor`,
    `qualifiers` as qualifiers,
    `edited` as edited,
    `value`,
    `personId` as person_id,
    `playerName` as player_name,
    `playerNameI` as player_name_initial,
    `jerseyNumber` as jersey_number,
    `x`,
    `y`,
    `xLegacy` as x_legacy,
    `yLegacy` as y_legacy,
    `area` as area,
    `areaDetail` as area_detail,
    `isFieldGoal` as is_field_goal,
    `shotDistance` as shot_distance,
    `shotValue` as shot_value,
    `shotResult` as shot_result,
    `pointsTotal` as points_total,
    `shotActionNumber` as shot_action_number,
    `assistPersonId` as assist_person_id,
    `assistFullName` as assist_full_name,
    `assistPlayerName` as assist_player_name,
    `assistPlayerNameInitial` as assist_player_name_initial,
    `assistTotal` as assist_total,
    `reboundTotal` as rebound_total,
    `reboundDefensiveTotal` as rebound_defensive_total,
    `reboundOffensiveTotal` as rebound_offensive_total,
    `turnoverTotal` as turnover_total,
    `stealPersonId` as steal_person_id,
    `stealFullName` as steal_full_name,
    `stealPlayerName` as steal_player_name,
    `stealTotal` as steal_total,
    `foulPersonalTotal` as foul_personal_total,
    `foulTechnicalTotal` as foul_technical_total,
    `foulDrawnPersonId` as foul_drawn_person_id,
    `foulDrawnFullName` as foul_drawn_full_name,
    `foulDrawnPlayerName` as foul_drawn_player_name,
    `blockPersonId` as block_person_id,
    `blockFullName` as block_full_name,
    `blockPlayerName` as block_player_name,
    `blockTotal` as block_total,
    `jumpBallRecoveredName` as jump_ball_recovered_name,
    `jumpBallRecoveredPersonId` as jump_ball_recovered_person_id,
    `jumpBallRecoveredFullName` as jump_ball_recovered_full_name,
    `jumpBallWonPersonId` as jump_ball_won_person_id,
    `jumpBallWonFullName` as jump_ball_won_full_name,
    `jumpBallWonPlayerName` as jump_ball_won_player_name,
    `jumpBallLostPersonId` as jump_ball_lost_person_id,
    `jumpBallLostFullName` as jump_ball_lost_full_name,
    `jumpBallLostPlayerName` as jump_ball_lost_player_name,
    `subsInPersonId` as subs_in_person_id,
    `subsInFullName` as subs_in_full_name,
    `subsInPlayerName` as subs_in_player_name,
    `officialId` as official_id,
    `videoAvailable` as video_available,
    `personIdsFilter` as person_ids_filter,
    `gameType` as game_type,
    `playerteamId` as player_team_id,
    `opponentteamId` as opponent_team_id,
    `jumpBallRecoverdPersonId` as jump_ball_recoverd_person_id,
    `gameDateTimeEst_g` as game_datetime_est_g,
    `gameType_g` as game_type_g

from {{ source('nba_raw', 'play_by_play') }}
